SELECT TOP 1 CITY, LEN(CITY) FROM STATION
ORDER BY LEN(CITY), CITY

SELECT TOP 1 CITY, LEN(CITY) FROM STATION
ORDER BY LEN(CITY) DESC, CITY

-- SELECT CITY, LEN(CITY) FROM STATION
-- WHERE CITY = (SELECT TOP 1 CITY FROM STATION ORDER BY LEN(CITY), CITY)
    -- OR CITY = (SELECT TOP 1 CITY FROM STATION ORDER BY LEN(CITY) DESC, CITY)